import type { Config } from 'tailwindcss';

const config: Config = {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        bg: {
          base: '#0A0E1A',
          card: '#121826',
          modal: '#1A1F2E',
        },
        border: {
          subtle: '#1E2433',
          default: '#2A3142',
        },
        text: {
          primary: '#FFFFFF',
          body: '#E4E7EB',
          muted: '#9CA3AF',
          faint: '#6B7280',
          receiptBody: '#4B5563',
        },
        brand: {
          yellow: '#FACC15',
          yellowDark: '#B45309',
          cyan: '#38BDF8',
          green: '#10B981',
          red: '#EF4444',
        },
        paper: {
          top: '#FAFAF7',
          bot: '#F4F4F0',
          ink: '#0A0E1A',
          divider: '#D1D5DB',
        },
      },
      fontFamily: {
        sans: ['"Space Grotesk"', 'system-ui', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'ui-monospace', 'monospace'],
        serif: ['"Instrument Serif"', 'Georgia', 'serif'],
      },
      borderRadius: {
        chip: '6px',
        btn: '8px',
        cta: '10px',
        card: '14px',
        cardLg: '16px',
        cardXL: '20px',
      },
      boxShadow: {
        receipt: '0 30px 80px rgba(250,204,21,.18), 0 0 0 1px rgba(250,204,21,.25)',
        receiptGreen: '0 30px 60px rgba(16,185,129,.2), 0 0 0 1px rgba(16,185,129,.4)',
        modal: '0 20px 60px rgba(0,0,0,.5)',
        stampLift: '0 4px 0 rgba(16,185,129,0.15)',
      },
      keyframes: {
        spin: { to: { transform: 'rotate(360deg)' } },
        'fade-up': {
          '0%': { opacity: '0', transform: 'translateY(12px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'connect-pulse': {
          '0%,100%': { boxShadow: '0 0 0 0 rgba(250,204,21,.5)' },
          '50%': { boxShadow: '0 0 0 16px rgba(250,204,21,0)' },
        },
        pulse: { '0%,100%': { opacity: '1' }, '50%': { opacity: '.5' } },
        'hero-shake': {
          '0%,32%,40%,100%': { transform: 'rotate(-1.5deg) translate(0,0)' },
          '33%': { transform: 'rotate(-1.5deg) translate(-6px, 4px)' },
          '35%': { transform: 'rotate(-1.5deg) translate(6px, -2px)' },
          '37%': { transform: 'rotate(-1.5deg) translate(-3px, 1px)' },
          '39%': { transform: 'rotate(-1.5deg) translate(2px, 0)' },
        },
        'hero-stamp': {
          '0%,15%': { opacity: '0', transform: 'translateY(-260px) translateX(40px) rotate(60deg) scale(2.6)' },
          '32%': { opacity: '1', transform: 'translateY(0) translateX(0) rotate(-8deg) scale(1.18)' },
          '36%': { opacity: '1', transform: 'translateY(0) translateX(0) rotate(-14deg) scale(0.92)' },
          '42%,90%': { opacity: '1', transform: 'translateY(0) translateX(0) rotate(-12deg) scale(1)' },
          '100%': { opacity: '0', transform: 'translateY(-260px) translateX(40px) rotate(60deg) scale(2.6)' },
        },
        'hero-splat': {
          '0%,30%': { opacity: '0', transform: 'translate(-50%,-50%) scale(0.4)' },
          '34%': { opacity: '.55', transform: 'translate(-50%,-50%) scale(1.4)' },
          '44%,100%': { opacity: '0', transform: 'translate(-50%,-50%) scale(2.4)' },
        },
        'stamp-drop': {
          '0%': { opacity: '0', transform: 'translateY(-220px) translateX(30px) rotate(60deg) scale(2.6)' },
          '55%': { opacity: '1', transform: 'translateY(0) translateX(0) rotate(-8deg) scale(1.2)' },
          '65%': { opacity: '1', transform: 'translateY(0) translateX(0) rotate(-14deg) scale(0.9)' },
          '100%': { opacity: '1', transform: 'translateY(0) translateX(0) rotate(-12deg) scale(1)' },
        },
        'stamp-shake': {
          '0%,55%,100%': { transform: 'rotate(-1deg) translate(0,0)' },
          '58%': { transform: 'rotate(-1deg) translate(-5px,3px)' },
          '62%': { transform: 'rotate(-1deg) translate(5px,-2px)' },
          '66%': { transform: 'rotate(-1deg) translate(-2px,1px)' },
          '70%': { transform: 'rotate(-1deg) translate(1px,0)' },
        },
        'stamp-splat': {
          '0%,50%': { opacity: '0', transform: 'translate(-50%,-50%) scale(.4)' },
          '58%': { opacity: '.55', transform: 'translate(-50%,-50%) scale(1.5)' },
          '80%,100%': { opacity: '0', transform: 'translate(-50%,-50%) scale(2.4)' },
        },
        'card-in': {
          '0%': { opacity: '0', transform: 'translateY(20px) scale(.95)' },
          '100%': { opacity: '1', transform: 'translateY(0) scale(1)' },
        },
        scan: { '0%': { transform: 'translateX(-100%)' }, '100%': { transform: 'translateX(100%)' } },
        'mini-orbit-1': { from: { transform: 'rotate(0deg) translateX(7px) rotate(0deg)' }, to: { transform: 'rotate(360deg) translateX(7px) rotate(-360deg)' } },
        'mini-orbit-2': { from: { transform: 'rotate(140deg) translateX(7px) rotate(-140deg)' }, to: { transform: 'rotate(500deg) translateX(7px) rotate(-500deg)' } },
        'mini-orbit-3': { from: { transform: 'rotate(260deg) translateX(7px) rotate(-260deg)' }, to: { transform: 'rotate(620deg) translateX(7px) rotate(-620deg)' } },
        'page-orbit-1': { from: { transform: 'rotate(0deg) translateX(56px) rotate(0deg)' }, to: { transform: 'rotate(360deg) translateX(56px) rotate(-360deg)' } },
        'page-orbit-2': { from: { transform: 'rotate(140deg) translateX(70px) rotate(-140deg)' }, to: { transform: 'rotate(500deg) translateX(70px) rotate(-500deg)' } },
        'page-orbit-3': { from: { transform: 'rotate(260deg) translateX(84px) rotate(-260deg)' }, to: { transform: 'rotate(620deg) translateX(84px) rotate(-620deg)' } },
        'btn-progress': { '0%': { width: '0' }, '70%': { width: '88%' }, '100%': { width: '100%' } },
        'btn-scan': { '0%': { transform: 'translateX(-100%)' }, '100%': { transform: 'translateX(100%)' } },
        'toast-in': { from: { opacity: '0', transform: 'translate(-50%,-20px)' }, to: { opacity: '1', transform: 'translate(-50%,0)' } },
        'backdrop-in': { from: { opacity: '0' }, to: { opacity: '1' } },
        'modal-in': {
          '0%': { opacity: '0', transform: 'translateY(40px) scale(.92)' },
          '60%': { opacity: '1', transform: 'translateY(0) scale(1.02)' },
          '100%': { opacity: '1', transform: 'translateY(0) scale(1)' },
        },
        'invoice-in': {
          '0%': { opacity: '0', transform: 'translateY(-12px) scale(.98)' },
          '100%': { opacity: '1', transform: 'translateY(0) scale(1)' },
        },
      },
      animation: {
        spin: 'spin 0.8s linear infinite',
        'fade-up': 'fade-up 0.4s ease-out',
        'connect-pulse': 'connect-pulse 2.5s ease-out infinite',
        pulse: 'pulse 2s ease-in-out infinite',
        'hero-shake': 'hero-shake 4.5s ease-out infinite',
        'hero-stamp': 'hero-stamp 4.5s cubic-bezier(.5,1.6,.5,1) infinite',
        'hero-splat': 'hero-splat 4.5s ease-out infinite',
        'stamp-drop': 'stamp-drop 0.7s cubic-bezier(.5,1.6,.5,1) forwards',
        'stamp-shake': 'stamp-shake 1.4s ease-out',
        'stamp-splat': 'stamp-splat 1.4s ease-out forwards',
        'card-in': 'card-in 0.4s ease-out',
        scan: 'scan 1.8s ease-in-out infinite',
        'mini-orbit-1': 'mini-orbit-1 1.1s linear infinite',
        'mini-orbit-2': 'mini-orbit-2 1.6s linear infinite',
        'mini-orbit-3': 'mini-orbit-3 2.2s linear infinite',
        'page-orbit-1': 'page-orbit-1 1.6s linear infinite',
        'page-orbit-2': 'page-orbit-2 2.4s linear infinite',
        'page-orbit-3': 'page-orbit-3 3.2s linear infinite',
        'btn-progress': 'btn-progress 1.4s ease-out forwards',
        'btn-scan': 'btn-scan 1.2s linear infinite',
        'toast-in': 'toast-in 0.3s ease-out',
        'backdrop-in': 'backdrop-in 0.25s ease-out',
        'modal-in': 'modal-in 0.5s cubic-bezier(.2,.9,.3,1.2)',
        'invoice-in': 'invoice-in 0.4s ease-out forwards',
      },
    },
  },
  plugins: [],
};
export default config;
